import { JobListing } from '../types';

export const jobCatalog: JobListing[] = [
  {
    id: 'job_junior_dev',
    title: 'Junior Developer',
    company: 'TechStart Inc',
    salary: 2800,
    hoursPerWeek: 40,
    tier: 1,
    description: 'Entry-level position for aspiring developers',
    requirements: ['Basic coding', 'Willingness to learn'],
    successChance: 85,
    requiredCreditScore: 600,
    requiredHousingTier: 1,
  },
  {
    id: 'job_mid_dev',
    title: 'Software Developer',
    company: 'CodeCorp',
    salary: 4200,
    hoursPerWeek: 40,
    tier: 2,
    description: 'Mid-level developer with project ownership',
    requirements: ['2+ years experience', 'Team collaboration'],
    successChance: 65,
    requiredCreditScore: 650,
    requiredHousingTier: 2,
  },
  {
    id: 'job_senior_dev',
    title: 'Senior Developer',
    company: 'MegaTech',
    salary: 6500,
    hoursPerWeek: 45,
    tier: 3,
    description: 'Lead complex projects and mentor junior devs',
    requirements: ['5+ years experience', 'Leadership skills', 'System design'],
    successChance: 45,
    requiredCreditScore: 700,
    requiredHousingTier: 3,
  },
  {
    id: 'job_architect',
    title: 'Solutions Architect',
    company: 'CloudSystems',
    salary: 9500,
    hoursPerWeek: 50,
    tier: 4,
    description: 'Design enterprise-scale architectures',
    requirements: ['8+ years experience', 'Cloud expertise', 'Strategic thinking'],
    successChance: 30,
    requiredCreditScore: 750,
    requiredHousingTier: 4,
  },
  {
    id: 'job_cto',
    title: 'Chief Technology Officer',
    company: 'StartupUnicorn',
    salary: 15000,
    hoursPerWeek: 60,
    tier: 5,
    description: 'Lead entire technology vision and team',
    requirements: ['10+ years experience', 'Executive leadership', 'Business acumen'],
    successChance: 15,
    requiredCreditScore: 800,
    requiredHousingTier: 5,
  },
];

export default jobCatalog;
